const types = {

  SET_FORM_ATTRIBUTE: 'SET_FORM_ATTRIBUTE',
  SET_ACTIVE_STEP: 'SET_ACTIVE_STEP',

  SET_LOCATIONS: 'SET_LOCATIONS',
  SET_RAW_LOCATIONS: 'SET_RAW_LOCATIONS',

};

export default types;
