const types = {

  SET_FORM_ATTRIBUTE: 'SET_FORM_ATTRIBUTE',
  SET_ACTIVE_STEP: 'SET_ACTIVE_STEP',
  RESET_ATTR: 'RESET_ATTR',

  SET_LOCATIONS: 'SET_LOCATIONS',
  SET_RAW_LOCATIONS: 'SET_RAW_LOCATIONS',

  SET_CONFIRM: 'SET_CONFIRM',

  SET_NAVIGATION: 'SET_NAVIGATION',
  SET_USER: 'SET_USER',

};

export default types;
